package helper

import (
	"strings"
	"time"

	"meta-egg/pkg/version"
)

const (
	PH_META_EGG_HEADER  = "%%META-EGG-HEADER%%"
	PH_META_EGG_CAUTION = "%%META-EGG-CAUTION%%"
	PH_META_EGG_EXPLAIN = "%%META-EGG-EXPLAIN%%"
	PH_META_EGG_VERSION = "%%META-EGG-VERSION%%"
	PH_NOW_DATE_TIME    = "%%NOW-DATE-TIME%%"
)

var TplHeader = `// Code generated by meta-egg. %%META-EGG-CAUTION%%
// %%META-EGG-EXPLAIN%%
// %%META-EGG-CAUTION%%
// Version: %%META-EGG-VERSION%%
// Author: meta-egg
// Generated at: %%NOW-DATE-TIME%%
`

func AddHeaderNoEdit(s string) string {
	code := strings.ReplaceAll(TplHeader, PH_META_EGG_CAUTION, "DO NOT EDIT.")
	code = strings.ReplaceAll(code, PH_META_EGG_EXPLAIN, "WILL BE replace after re-generated!")
	code = strings.ReplaceAll(code, PH_META_EGG_VERSION, version.GetVersion())
	code = strings.ReplaceAll(code, PH_NOW_DATE_TIME, time.Now().Format("2006-01-02 15:04"))
	return strings.ReplaceAll(s, PH_META_EGG_HEADER, code)
}

func AddHeaderCanEdit(s string) string {
	code := strings.ReplaceAll(TplHeader, PH_META_EGG_CAUTION, "CAREFULLY EDIT.")
	code = strings.ReplaceAll(code, PH_META_EGG_EXPLAIN, "WILL NOT BE replace after re-generated, unless you confirm it!")
	code = strings.ReplaceAll(code, PH_META_EGG_VERSION, version.GetVersion())
	code = strings.ReplaceAll(code, PH_NOW_DATE_TIME, time.Now().Format("2006-01-02 15:04"))
	return strings.ReplaceAll(s, PH_META_EGG_HEADER, code)
}
