version: 2

project_name: meta-egg
release:
  github:
    owner: Jinglever
    name: meta-egg

builds:
  - id: meta-egg
    main: ./cmd/meta-egg
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags: >-
      -s -w
      -X "meta-egg/pkg/version.BuildTS={{ .Date }}"
      -X "meta-egg/pkg/version.GitHash={{ .Commit }}"
      -X "meta-egg/pkg/version.GitBranch={{ .Branch }}"
      -X "meta-egg/pkg/version.GitTag={{ .Tag }}"
      -X "meta-egg/pkg/version.GitDirty=false"
      -X "meta-egg/pkg/version.Debug=false"
    flags: -trimpath
    env:
      - CGO_ENABLED=0

archives:
  - formats: [ 'zip' ]
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

brews:
  - name: meta-egg
    directory: Formula
    repository:
      owner: Jinglever
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/Jinglever/meta-egg"
    description: "Awesome Tools to Generate MetaEgg Framework"
    commit_author:
      name: meta-egg-bot
      email: zhihao.zhou.bupt@gmail.com
    install: |
      bin.install "meta-egg"
      generate_completions_from_executable("#{bin}/meta-egg", "completion")
    test: |
      system "#{bin}/meta-egg" "--version"