package template

const (
	// basic
	PH_GO_MODULE         = "%%GO-MODULE%%"
	PH_TABLE_NAME        = "%%TABLE-NAME%%"
	PH_STRUCT_TABLE_NAME = "%%TABLE-NAME-STRUCT%%"
	PH_TABLE_NAME_VAR    = "%%TABLE-NAME-VAR%%" // 适用于变量名, 驼峰, 首字母小写
	PH_TPL_FUNC_CREATE   = "%%TPL-FUNC-CREATE%%"
	PH_TPL_FUNC_GET_LIST = "%%TPL-FUNC-GET-LIST%%"
	PH_TPL_FUNC_UPDATE   = "%%TPL-FUNC-UPDATE%%"
	PH_TPL_FUNC_DELETE   = "%%TPL-FUNC-DELETE%%"
	PH_COMMENT_REPO      = "%%COMMENT-REPO%%"

	// dynamic generate
	PH_REPO_LIST_IN_STRUCT        = "%%REPO-LIST-IN-STRUCT%%"
	PH_REPO_LIST_IN_ARG           = "%%REPO-LIST-IN-ARG%%" // 在函数参数中
	PH_ASSIGN_REPO_LIST           = "%%ASSIGN-REPO-LIST%%" // 为结构体赋值
	PH_FILTER_COL_LIST            = "%%FILTER-COL-LIST%%"
	PH_FILTER_GET_REPO_OPTIONS    = "%%FILTER-GET-REPO-OPTIONS%%"
	PH_ORDER_BY_LIST              = "%%ORDER-BY-LIST%%"
	PH_SET_COL_LIST               = "%%SET-COL-LIST%%"
	PH_SET_UPDATE_SETCVS          = "%%SET-UPDATE-SETCVS%%"
	PH_CREATE_ERROR_DUPLICATE_KEY = "%%CREATE-ERROR-DUPLICATE-KEY%%"
	PH_UPDATE_ERROR_DUPLICATE_KEY = "%%UPDATE-ERROR-DUPLICATE-KEY%%"

	PH_COL_LIST_IN_BO                = "%%COL-LIST-IN-BO%%"
	PH_PREPARE_ASSIGN_MODEL_TO_BO    = "%%PREPARE-ASSIGN-MODEL-TO-BO%%"
	PH_ASSIGN_MODEL_TO_BO            = "%%ASSIGN-MODEL-TO-BO%%"
	PH_PREPARE_ASSIGN_BO_TO_MODEL    = "%%PREPARE-ASSIGN-BO-TO-MODEL%%"
	PH_ASSIGN_BO_TO_MODEL            = "%%ASSIGN-BO-TO-MODEL%%"
	PH_COL_LIST_FOR_LIST             = "%%COL-LIST-FOR-LIST%%"
	PH_PREPARE_ASSIGN_MODEL_FOR_LIST = "%%PREPARE-ASSIGN-MODEL-FOR-LIST%%"
	PH_ASSIGN_MODEL_FOR_LIST         = "%%ASSIGN-MODEL-FOR-LIST%%"

	PH_ASSIGN_FILTER_TO_OPTION     = "%%ASSIGN-FILTER-TO-OPTION%%"
	PH_COL_LIST_TO_SELECT_FOR_LIST = "%%COL-LIST-TO-SELECT-FOR-LIST%%"

	// RL table related placeholders
	PH_RL_BO_FIELDS               = "%%RL-BO-FIELDS%%"
	PH_RL_LIST_BO_FIELDS          = "%%RL-LIST-BO-FIELDS%%"
	PH_RL_ASSIGN_MODEL_TO_BO      = "%%RL-ASSIGN-MODEL-TO-BO%%"
	PH_RL_ASSIGN_MODEL_TO_LIST_BO = "%%RL-ASSIGN-MODEL-TO-LIST-BO%%"
	PH_RL_METHODS                 = "%%RL-METHODS%%"
	PH_RL_BO_DEFINITIONS          = "%%RL-BO-DEFINITIONS%%"
	PH_RL_LIST_BO_DEFINITIONS     = "%%RL-LIST-BO-DEFINITIONS%%"
	PH_RL_CREATE_IN_TRANSACTION   = "%%RL-CREATE-IN-TRANSACTION%%"

	// 新增级联删除占位符
	PH_RL_CASCADE_DELETE_IN_BIZ = "%%RL-CASCADE-DELETE-IN-BIZ%%"

	// BR table cascade unbind placeholder
	PH_BR_CASCADE_UNBIND_IN_BIZ = "%%BR-CASCADE-UNBIND-IN-BIZ%%"

	// BR table related placeholders
	PH_BR_OPTIONS = "%%BR-OPTIONS%%"
	PH_BR_METHODS = "%%BR-METHODS%%"

	// BR table biz layer placeholders (for BR table's own biz file)
	PH_BR_RELATION_METHODS = "%%BR-RELATION-METHODS%%"
)
