package template

const (
	PH_GO_MODULE                          = "%%GO-MODULE%%"
	PH_ENV_PREFIX                         = "%%ENV-PREFIX%%"
	PH_TPL_CONF_YML_RESOURCE_DB           = "%%TPL-CONF-YML-RESOURCE-DB%%"
	PH_TPL_CONF_YML_HTTP_SERVER           = "%%TPL-CONF-YML-HTTP-SERVER%%"
	PH_TPL_CONF_YML_GRPC_SERVER           = "%%TPL-CONF-YML-GRPC-SERVER%%"
	PH_TPL_CONFIG_STRUCT_HTTP_SERVER      = "%%TPL-CONFIG-STRUCT-HTTP-SERVER%%"
	PH_TPL_CONFIG_STRUCT_GRPC_SERVER      = "%%TPL-CONFIG-STRUCT-GRPC-SERVER%%"
	PH_TPL_CONFIG_FUNC_GET_HTTP_SERVER    = "%%TPL-CONFIG-FUNC-GET-HTTP-SERVER%%"
	PH_TPL_CONFIG_FUNC_GET_GRPC_SERVER    = "%%TPL-CONFIG-FUNC-GET-GRPC-SERVER%%"
	PH_TPL_DB_TYPE                        = "%%TPL-DB-TYPE%%"
	PH_TPL_DB_DSN                         = "%%TPL-DB-DSN%%"
	PH_TPL_CONF_YML_RESOURCE_ACCESS_TOKEN = "%%TPL-CONF-YML-RESOURCE-ACCESS-TOKEN%%"

	PH_TPL_CONF_YML_HTTP_SERVER_ACCESS_TOKEN = "%%TPL-CONF-YML-HTTP-SERVER-ACCESS-TOKEN%%"
	PH_TPL_CONF_YML_GRPC_SERVER_ACCESS_TOKEN = "%%TPL-CONF-YML-GRPC-SERVER-ACCESS-TOKEN%%"
)
