package template

const (
	PH_IMPORTS = "%%IMPORTS%%"

	PH_GO_MODULE = "%%GO-MODULE%%"

	PH_NEW_REPO_FUNC_LIST_IN_PROVIDER_SET      = "%%NEW-REPO-FUNC-LIST-IN-PROVIDER-SET%%"
	PH_NEW_REPO_FUNC_LIST_IN_MOCK_PROVIDER_SET = "%%NEW-REPO-FUNC-LIST-IN-MOCK-PROVIDER-SET%%"

	PH_TABLE_NAME        = "%%TABLE-NAME%%"
	PH_STRUCT_TABLE_NAME = "%%TABLE-NAME-STRUCT%%"
	PH_COL_ID            = "%%COL-ID%%"
	PH_COL_UPDATED_BY    = "%%COL-UPDATED-BY%%"
	PH_COL_DELETED_BY    = "%%COL-DELETED-BY%%"
	PH_COL_DELETED_AT    = "%%COL-DELETED-AT%%"
	PH_VAL_DELETED_AT    = "%%VAL-DELETED-AT%%"

	PH_TPL_SETUP_ME_FOR_CREATE       = "%%TPL-SETUP-ME-FOR-CREATE%%"
	PH_TPL_SETUP_ME_FOR_CREATE_BATCH = "%%TPL-SETUP-ME-FOR-CREATE-BATCH%%"
	PH_SET_ME_FOR_CREATE             = "%%SET-ME-FOR-CREATE%%"
	PH_TPL_SETUP_ME_FOR_UPDATE       = "%%TPL-SETUP-ME-FOR-UPDATE%%"
	PH_TPL_DELETE                    = "%%TPL-DELETE%%"

	PH_CASE_META_ID_TO_SEMANTIC = "%%CASE-META-ID-TO-SEMANTIC%%"
	PH_CASE_META_SEMANTIC_TO_ID = "%%CASE-META-SEMANTIC-TO-ID%%"
	PH_ORDER_BY_LIST            = "%%ORDER-BY-LIST%%"
	PH_FILTER_COL_LIST          = "%%FILTER-COL-LIST%%"
	PH_FILTER_GET_REPO_OPTIONS  = "%%FILTER-GET-REPO-OPTIONS%%"
)
