package template

const (
	// basic
	PH_GO_MODULE           = "%%GO-MODULE%%"
	PH_PROJECT_NAME        = "%%PROJECT-NAME%%"
	PH_PROJECT_NAME_DIR    = "%%PROJECT-NAME-DIR%%"    // 适用于目录名
	PH_PROJECT_NAME_STRUCT = "%%PROJECT-NAME-STRUCT%%" // 适用于结构体名
	PH_PROJECT_NAME_PKG    = "%%PROJECT-NAME-PKG%%"    // 适用于包名
	PH_TABLE_COMMENT       = "%%TABLE-COMMENT%%"
	PH_TABLE_NAME_URI      = "%%TABLE-NAME-URI%%"
	PH_TABLE_NAME_STRUCT   = "%%TABLE-NAME-STRUCT%%"
	PH_COMMENT_DOMAIN      = "%%COMMENT-DOMAIN%%"
	PH_COMMENT_REPO        = "%%COMMENT-REPO%%"

	// dynamic
	PH_HTTP_ROUTE_MAPPING                  = "%%HTTP-ROUTE-MAPPING%%"
	PH_IMPORT_HDL_COMMENT                  = "%%IMPORT-HDL-COMMENT%%"
	PH_TPL_FUNC_GRPC_AUTH_INTERCEPTOR      = "%%TPL-FUNC-GRPC-AUTH-INTERCEPTOR%%"
	PH_TPL_CALL_FUNC_GRPC_AUTH_INTERCEPTOR = "%%TPL-CALL-FUNC-GRPC-AUTH-INTERCEPTOR%%"
	PH_TPL_FUNC_HTTP_AUTH_HANDLER          = "%%TPL-FUNC-HTTP-AUTH-HANDLER%%"
	PH_HTTP_ROUTE_USE_AUTH_HANDLER         = "%%HTTP-ROUTE-USE-AUTH-HANDLER%%"
	PH_TPL_GRPC_SERVER_CONFIG_ACCESS_TOKEN = "%%TPL-GRPC-SERVER-CONFIG-ACCESS-TOKEN%%"
	PH_TPL_HTTP_SERVER_CONFIG_ACCESS_TOKEN = "%%TPL-HTTP-SERVER-CONFIG-ACCESS-TOKEN%%"
)
