name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build and Upload Binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.8' # or your preferred Go version

      - name: Build binary with version info
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          GOMODULE=meta-egg
          BUILD_TS=$(date -u '+%Y-%m-%d %H:%M:%S')
          GIT_HASH=$(git rev-parse HEAD)
          GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          GIT_TAG=$(git describe --tags --abbrev=0 --exact-match 2>/dev/null || true)
          GIT_DIRTY=$(test -n "$(git status --porcelain)" && echo "true" || echo "false")
          DEBUG="false"
          LDFLAGS="-X \"${GOMODULE}/pkg/version.BuildTS=${BUILD_TS}\""
          LDFLAGS="$LDFLAGS -X \"${GOMODULE}/pkg/version.GitHash=${GIT_HASH}\""
          LDFLAGS="$LDFLAGS -X \"${GOMODULE}/pkg/version.GitBranch=${GIT_BRANCH}\""
          LDFLAGS="$LDFLAGS -X \"${GOMODULE}/pkg/version.GitTag=${GIT_TAG}\""
          LDFLAGS="$LDFLAGS -X \"${GOMODULE}/pkg/version.GitDirty=${GIT_DIRTY}\""
          LDFLAGS="$LDFLAGS -X \"${GOMODULE}/pkg/version.Debug=${DEBUG}\""
          GO_LDFLAGS="-s -w"
          GO_TRIMPATH="-trimpath"
          if [ "${{ matrix.goos }}" = "windows" ]; then
            go build -ldflags "${GO_LDFLAGS} ${LDFLAGS}" ${GO_TRIMPATH} -o meta-egg.exe ./cmd/meta-egg/
          else
            go build -ldflags "${GO_LDFLAGS} ${LDFLAGS}" ${GO_TRIMPATH} -o meta-egg ./cmd/meta-egg/
          fi

      - name: Package binary
        run: |
          if [ "${{ matrix.goos }}" = "windows" ]; then
            zip meta-egg-${{ matrix.goos }}-${{ matrix.goarch }}.zip meta-egg.exe
          else
            tar -czvf meta-egg-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz meta-egg
          fi

      - name: Upload Release Asset
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: ${{ github.ref_name }}
          artifacts: |
            meta-egg-*.zip
            meta-egg-*.tar.gz